version: "3.8"

services:
  db:
    image: postgres:16-alpine
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"

  api:
    build: .
    restart: always
    environment:
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: postgres
    depends_on:
      - db
    ports:
      - "8080:8080"
    volumes:
      - app-data:/app

volumes:
  db-data:
  app-data: